<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kategori extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Kategori_m');
    } 

    /*
     * Listing of kategori
     */
    function index()
    {
        $data['kategori'] = $this->Kategori_m->get_all_kategori();
        
        $data['_view'] = 'kategori/index';
        $this->template->load('gudang/adminTemplate','gudang/kategori/index',$data);
    }

    /*
     * Adding a new kategori
     */
    function add()
    {   
        $this->load->library('form_validation');

        $this->form_validation->set_rules('kategori','Kategori','required|max_length[25]');
        
        if($this->form_validation->run())     
            {   
                $params = array(
            'kategori' => $this->input->post('kategori'),
                );
                
                $kategori_id = $this->Kategori_m->add_kategori($params);
                redirect('gudang/kategori/index');
            }
            else
            {            
                $data['_view'] = 'kategori/add';
            $this->template->load('gudang/adminTemplate','gudang/kategori/index',$data);
            }
    }  

    /*
     * Editing a kategori
     */
    function edit($id_kategori)
    {   
        // check if the kategori exists before trying to edit it
        $data['kategori'] = $this->Kategori_m->get_kategori($id_kategori);
        
        if(isset($data['kategori']['id_kategori']))
        {
            $this->load->library('form_validation');

      $this->form_validation->set_rules('kategori','Kategori','required|max_length[25]');
    
      if($this->form_validation->run())     
            {   
                $params = array(
          'kategori' => $this->input->post('kategori'),
                );

                $this->Kategori_m->update_kategori($id_kategori,$params);            
                redirect('gudang/kategori/index');
            }
            else
            {
                $data['_view'] = 'gudang/kategori/edit';
        $this->template->load('gudang/adminTemplate','gudang/kategori/edit',$data);
            }
        }
        else
            show_error('The kategori you are trying to edit does not exist.');
    } 

    /*
     * Deleting kategori
     */
    function remove($id_kategori)
    {
        $kategori = $this->Kategori_m->get_kategori($id_kategori);

        // check if the kategori exists before trying to delete it
        if(isset($kategori['id_kategori']))
        {
            $this->Kategori_m->delete_kategori($id_kategori);
            redirect('gudang/kategori/index');
        }
        else
            show_error('The kategori you are trying to delete does not exist.');
    }
    
}
