<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Barang_m extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get barang by id_barang
     */
    function get_barang($id_barang)
    {
        return $this->db->get_where('barang',array('id_barang'=>$id_barang))->row_array();
    }
        
    /*
     * Get all barang
     */
    function get_all_barang()
    { 
        $this->db->select('a.id_barang, b.kategori, c.spek, a.serial_no, a.nama_barang, a.kondisi, a.status, a.barcode ');
        $this->db->from('barang a');
        $this->db->join('kategori b','a.id_kategori=b.id_kategori');
        $this->db->join('spek c','a.id_spek = c.id_spek');
        $query = $this->db->get();
        return $query->result_array();
    }
        
    /*
     * function to update barang
     */
    function update_barang($id_barang,$params)
    {
        $this->db->where('id_barang',$id_barang);
        return $this->db->update('barang',$params);
    }
    
    /*
     * function to delete barang
     */
    function delete_barang($id_barang)
    {
        return $this->db->delete('barang',array('id_barang'=>$id_barang));
    }

    function save_barang($id_kategori,$id_spek,$serial_no,$nama_barang,$kondisi,$status,$image_name)
    {
        $data = array(
            'id_kategori'       => $id_kategori,
            'id_spek'      => $id_spek,
            'nama_barang'     => $nama_barang, 
            'serial_no'     => $serial_no, 
            'kondisi'     => $kondisi, 
            'status'     => $status, 
            'nama_barang'     => $nama_barang, 
            'barcode'   => $image_name
        );
        $this->db->insert('barang',$data);
    }

    function save_barang_update($id_barang,$id_kategori,$id_spek,$serial_no,$nama_barang,$kondisi,$status,$image_name)
    {
        $data = array(
            'id_kategori'       => $id_kategori,
            'id_spek'      => $id_spek,
            'nama_barang'     => $nama_barang, 
            'serial_no'     => $serial_no, 
            'kondisi'     => $kondisi, 
            'status'     => $status, 
            'nama_barang'     => $nama_barang, 
            'barcode'   => $image_name
        );
        $this->db->where('id_barang',$id_barang);
        return $this->db->update('barang',$data);
    }

     function get_kategori()
    {
         $query = $this->db->get('kategori')->result_array();
         return $query;
    }
 
    function get_spek() 
    {
  
    $query = $this->db->get('spek');
    return $query->result();
    }
}
