<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Company_m extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get konsumen by id_company_konsumen
     */
    function get_company($id_company)
    {
        return $this->db->get_where('company',array('id_company'=>$id_company))->row_array();
    }
        
    /*
     * Get all konsumen
     */
    function get_all_company()
    {
        $this->db->order_by('id_company', 'desc');
        return $this->db->get('company')->result_array();
    }
        
    /*
     * function to add new konsumen
     */

    function add_company($data){
        $this->db->insert('company',$data);
    }
    
   /*
     * function to update konsuman
     */
    function update_company($id_company,$params)
    {
        $this->db->where('id_company',$id_company);
        return $this->db->update('company',$params);
    }
    
    /*
     * function to delete konsuman
     */
    function delete_company($id_company)
    {
        return $this->db->delete('company',array('id_company'=>$id_company));
    }
}
