<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Identitas_m extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get identitas by id_identitas
     */
    function get_identitas($id_identitas)
    {
        return $this->db->get_where('identitas',array('id_identitas'=>$id_identitas))->row_array();
    }
        
    /*
     * Get all identitas
     */
    function get_all_identitas()
    {
        $this->db->order_by('id_identitas', 'desc');
        return $this->db->get('identitas')->result_array();
    }
        
    /*
     * function to add new identitas
     */
    function add_identitas($params)
    {
        $this->db->insert('identitas',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update identitas
     */
    function update_identitas($id_identitas,$params)
    {
        $this->db->where('id_identitas',$id_identitas);
        return $this->db->update('identitas',$params);
    }
    
    /*
     * function to delete identitas
     */
    function delete_identitas($id_identitas)
    {
        return $this->db->delete('identitas',array('id_identitas'=>$id_identitas));
    }
}