<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Spek_m extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get spek by id_spek
     */
    function get_spek($id_spek)
    {
        return $this->db->get_where('spek',array('id_spek'=>$id_spek))->row_array();
    }
        
    /*
     * Get all spek
     */
    function get_all_spek()
    {
        $this->db->select('a.spek, a.id_spek, b.kategori');
        $this->db->from('spek a');
        $this->db->join('kategori b', 'a.id_kategori = b.id_kategori');
        $query = $this->db->get();
        return $query->result_array();
    }
        
    /*
     * function to add new spek
     */
    function add_spek($params)
    {
        $this->db->insert('spek',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update spek
     */
    function update_spek($id_spek,$params)
    {
        $this->db->where('id_spek',$id_spek);
        return $this->db->update('spek',$params);
    }
    
    /*
     * function to delete spek
     */
    function delete_spek($id_spek)
    {
        return $this->db->delete('spek',array('id_spek'=>$id_spek));
    }
}
