<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Company extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Company_m');
        $this->load->library('upload');
    } 

    /*
     * Listing of konsumen
     */
    function index()
    {
        $data['company'] = $this->Company_m->get_all_company();
        
        $data['_view'] = 'admin/company/index';
        $this->template->load('admin/adminTemplate','admin/company/index',$data);
    }

     function patnolpat()
    {
        $this->template->load('adminTemplate','auth/patnolpat',$data);
    }

    /*
     * Deleting konsumen
     */
    function remove($id_company)
    {
        $company = $this->Company_m->get_company($id_company);

        // check if the barang exists before trying to delete it
        if(isset($company['id_company']))
        {
            $this->Company_m->delete_company($id_company);
            redirect('admin/company/index');
        }
        else
            show_error('The barang you are trying to delete does not exist.');
    }

    function save()
    {
        $this->form_validation->set_rules('nama_comp', 'nama_comp', 'required');
        $this->form_validation->set_rules('no_telp_comp', 'no_telp_comp', 'required');
        $this->form_validation->set_rules('email_comp', 'email_comp', 'required');
        $this->form_validation->set_rules('alamat_comp', 'alamat_comp', 'required');
        $this->form_validation->set_error_delimiters('<span class="text-danger">','</span>');

        $this->load->library('upload');
        $config['upload_path'] ='./assets/company/';
        $config['allowed_types'] = 'gif|jpg|png|jpeg';
        $config['max_size'] = '2048';
        $config['max_wid_companyth'] = '1600';
        $config['max_height'] = '1200';
        $nama_file = "logo".time();
        $config['file_name'] = $nama_file;

        $this->upload->initialize($config);

        if ($_FILES['logo']['name']) 
        {
        
                $filed_name = "logo";
                if ($this->form_validation->run() && $this->upload->do_upload($filed_name))
                {
                    $nama_comp = $this->input->post('nama_comp');
                    $no_telp_comp = $this->input->post('no_telp_comp');
                    $email_comp = $this->input->post('email_comp');
                    $alamat_comp = $this->input->post('alamat_comp');

                    $logo = $this->upload->data();
                    $company = ([
                        'nama_comp'=>$nama_comp,
                        'no_telp_comp'=>$no_telp_comp,
                        'email_comp'=>$email_comp,
                        'alamat_comp'=>$alamat_comp,
                        'logo'=>$logo['file_name']]);
                    $data = array_merge($company);
                    if ($this->Company_m->add_company($data) == false) 
                    {
                        $this->session->set_flashdata('pesan', 'data disimpan');
                        redirect('admin/company/index');
                    }
                    else
                    {
                        $this->index();
                    }
                }
                else
                {
                    $this->index();
                }

        }

    }

}
    
