<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Konsumen extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Konsumen_m');
        $this->load->library('upload');
    } 

    /*
     * Listing of konsumen
     */
    function index()
    {
        $data['konsumen'] = $this->Konsumen_m->get_all_konsumen();
        
        $data['_view'] = 'admin/konsumen/index';
        $this->template->load('admin/adminTemplate','admin/konsumen/index',$data);
    }

     function patnolpat()
    {
        $this->template->load('adminTemplate','auth/patnolpat',$data);
    }

       public function do_upload()
        {
                $config['upload_path']          = './uploads/';
                $config['allowed_types']        = 'gif|jpg|png';
                $config['max_size']             = 100;
                $config['max_width']            = 1024;
                $config['max_height']           = 768;

                $this->load->library('upload', $config);

                if ( ! $this->upload->do_upload('userfile'))
                {
                        $error = array('error' => $this->upload->display_errors());

                        $this->load->view('upload_form', $error);
                }
                else
                {
                        $data = array('upload_data' => $this->upload->data());

                        $this->load->view('upload_success', $data);
                }
        }

    /*
     * Adding a new konsumen
     */

    /*
     * Editing a konsumen
     */
    function edit($id_konsumen)
    {   
        // check if the konsumen exists before trying to edit it
        $data['konsumen'] = $this->Konsumen_m->get_konsumen($id_konsumen);
        
        if(isset($data['konsumen']['id_konsumen']))
        {
            $this->load->library('form_validation');

      $this->form_validation->set_rules('konsumen','Konsumen','required|max_length[25]');
      $this->form_validation->set_rules('perusahaan','Perusahaan','required|max_length[25]');
      $this->form_validation->set_rules('no_telp','No Telephone','required|max_length[25]');
      $this->form_validation->set_rules('email','Email','required|max_length[25]');
      $this->form_validation->set_rules('alamat','alamat','required|max_length[25]');
    
      if($this->form_validation->run())     
            {   
                $params = array(
                                'konsumen' => $this->input->post('konsumen'),
                                'perusahaan' => $this->input->post('perusahaan'),
                                'no_telp' => $this->input->post('no_telp'),
                                'email' => $this->input->post('email'),
                                'alamat' => $this->input->post('alamat')
                );

               $this->Konsumen_m->update_konsumen($id_konsumen,$params);              
                redirect('admin/konsumen/index');
            }
            else
            {
                $data['_view'] = 'admin/konsumen/edit';
        $this->template->load('admin/adminTemplate','admin/konsumen/edit',$data);
            }
        }
        else
            show_error('The konsumen you are trying to edit does not exist.');
    } 

    /*
     * Deleting konsumen
     */
    function remove($id_konsumen)
    {
        $konsumen = $this->Konsumen_m->get_konsumen($id_konsumen);

        // check if the barang exists before trying to delete it
        if(isset($konsumen['id_konsumen']))
        {
            $this->Konsumen_m->delete_konsumen($id_konsumen);
            redirect('admin/konsumen/index');
        }
        else
            show_error('The barang you are trying to delete does not exist.');
    }

    function save()
    {
        $this->form_validation->set_rules('konsumen', 'konsumen', 'required');
        $this->form_validation->set_rules('perusahaan', 'perusahaan', 'required');
        $this->form_validation->set_rules('no_telp', 'no_telp', 'required');
        $this->form_validation->set_rules('email', 'email', 'required');
        $this->form_validation->set_rules('alamat', 'alamat', 'required');
        $this->form_validation->set_error_delimiters('<span class="text-danger">','</span>');

        $this->load->library('upload');
        $config['upload_path'] ='./assets/dokumen/';
        $config['allowed_types'] = 'gif|jpg|png|jpeg';
        $config['max_size'] = '2048';
        $config['max_width'] = '1600';
        $config['max_height'] = '1200';
        $nama_file = "gambar".time();
        $config['file_name'] = $nama_file;

        $this->upload->initialize($config);

        if ($_FILES['dokumen']['name']) 
        {
        
                $filed_name = "dokumen";
                if ($this->form_validation->run() && $this->upload->do_upload($filed_name))
                {
                    $konsumen = $this->input->post('konsumen');
                    $perusahaan = $this->input->post('perusahaan');
                    $no_telp = $this->input->post('no_telp');
                    $email = $this->input->post('email');
                    $alamat = $this->input->post('alamat');

                    $gambar = $this->upload->data();
                    $konsumenn = ([
                        'konsumen'=>$konsumen,
                        'perusahaan'=>$perusahaan,
                        'no_telp'=>$no_telp,
                        'email'=>$email,
                        'alamat'=>$alamat,
                        'dokumen'=>$gambar['file_name']]);
                    $data = array_merge($konsumenn);
                    if ($this->Konsumen_m->add_konsumen($data) == false) 
                    {
                        $this->session->set_flashdata('pesan', 'data disimpan');
                        redirect('admin/konsumen/index');
                    }
                    else
                    {
                        $this->index();
                    }
                }
                else
                {
                    $this->index();
                }

        }

    }

}
    
