<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pinjam extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Pinjam_m');
    } 

    /*
     * Listing of pinjam
     */
    function index()
    {
        $data['pinjam'] = $this->Pinjam_m->get_all_pinjam();
        $data['_view'] = 'pinjam/index';
        $this->template->load('admin/adminTemplate','admin/pinjam/index',$data);
    }

    /*
     * Adding a new pinjam
     */
    function add()
    {   
        if(isset($_POST['submit']))
        {
            $this->Pinjam_m->simpan_barang();
            redirect('admin/pinjam/add');
        }

        $data['detail']= $this->Pinjam_m->tampilkan_detail_transaksi()->result();
        $data['invoice'] = $this->Pinjam_m->get_no_invoice();
        
        $this->load->model('Barang_m');
        $data['all_barang'] = $this->Barang_m->get_all_barang();

        $data['_view'] = 'pinjam/add';
        $this->template->load('admin/adminTemplate','admin/pinjam/add',$data);
        // }
    }  

    function checkout() 
    {
        $this->template->load('admin/adminTemplate','admin/pinjam/checkout');
    }

    function tambah()
    {
        $data_produk= array('id' => $this->input->post('id'),
                             'name' => $this->input->post('nama'),
                             'price' => $this->input->post('harga'),
                             'gambar' => $this->input->post('gambar'),
                             'qty' =>$this->input->post('qty')
                            );
        $this->cart->insert($data_produk);
        redirect('admin/pinjam/add');
    
}

      function selesai_belanja()
    {
        $tanggal=date('Y-m-d');
        $user=  $this->session->userdata('username');
        $id_user=  $this->db->get_where('user',array('username'=>$user))->row_array();
        $data=array(
                    'no_invoice'=>$no_invoice,
                    // 'id_user'=>$id_user['id_user'],
                    'tanggal_invoice'=>$tanggal,
                    'tanggal_tempo' =>$tanggal_tempo,
                    );
        $this->Pinjam_m->selesai_belanja($data);
        redirect('admin/pinjam/add');
    }
    
}
